FROM node:14-alpine

WORKDIR /usr/app

COPY package*.json ./

RUN apk add --no-cache --virtual .gyp python make g++ \
    && npm install --only=production && apk del .gyp

COPY _services _services
COPY index.js ./
CMD ["node", "--icu-data-dir=node_modules/full-icu", "index.js"]