FROM node:16-alpine as backend_builder
WORKDIR /usr/app
COPY package*.json ./
RUN npm install
COPY tsconfig.json ./
COPY index.ts ./
COPY interfaces interfaces
COPY constants constants
COPY services services
RUN npm run build

# Server
FROM node:16-alpine
WORKDIR /usr/app
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install --only=production
COPY --from=backend_builder /usr/app/dist /usr/app
CMD ["node", "--icu-data-dir=node_modules/full-icu", "index.js"]