FROM node:14-alpine as frontend_builder
WORKDIR /usr/app
COPY client/package*.json ./
COPY client/src src
COPY client/public public
RUN npm install
RUN npm run build

# Server
FROM nginx:stable-alpine
COPY --from=frontend_builder /usr/app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]