FROM node:14-alpine

WORKDIR /usr/app

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY index.ts ./
COPY interfaces interfaces
COPY constants constants
COPY services services

RUN npm run build
RUN npm install --only=production
CMD ["node", "--icu-data-dir=node_modules/full-icu", "dist/index.js"]