FROM node:16-alpine as frontend_builder
WORKDIR /usr/app
COPY client/package*.json ./
COPY client/tsconfig.json ./
COPY client/Gruntfile.js ./
COPY client/src src
COPY client/public public
RUN npm install && npm install -g grunt-cli
RUN npm run build
RUN grunt

# Server
FROM nginx-with-brotli
RUN rm -rf /usr/share/nginx/html/*
COPY --from=frontend_builder /usr/app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]